### ISSUE TITLE
GitHubFlavored turns one linebreak into two

### ISSUE THREAD

**Issue by ImportTaste** [suntong/html2md#15] opened 2023-05-03 23:49 UTC
On GitHub's markdown, a single linebreak parsed as a single linebreak. But when running `html2md` I'm finding that it's turning one `<br>` tag into two linebreaks in the resulting md file.

**Comment by suntong** [comment] 2023-05-04 02:15
Please provide a Minimal, Reproducible Example

**Comment by suntong** [comment] 2023-05-04 03:29
thx. This looks like an upstream issue, which I've reported for you just now.

**Comment by suntong** [comment] 2023-05-09 22:15
This is an upstream issue and should be fixed upstream.

As for the rule, it has to be compiled in, not loading a source `.go` file on the fly.

**Comment by suntong** [comment] 2023-05-10 22:54
Closing it as it is the _"expected behavior"_ of upstream.

>  This is expected behavior. A line break in Markdown requires two newline characters. A single newline character will not render as a line break, instead it will render as a space.

_Originally posted by @wcalandro in https://github.com/JohannesKaufmann/html-to-markdown/issues/40#issuecomment-1012624554_

> Any chance of getting a parameter for this?

adding parameters won't fix the problem; unless it is fixed upstream. 

For further communicating about this issue, please conduct at upstream https://github.com/JohannesKaufmann/html-to-markdown/issues/40

**Closed by suntong** 2023-05-10 22:54 UTC
Labels: upstream

**Comment by suntong** [comment] 2023-05-10 23:16
For further communicating about this issue, **please conduct at upstream** JohannesKaufmann/html-to-markdown#40

IE, take a look my comment -- https://github.com/JohannesKaufmann/html-to-markdown/issues/40#issuecomment-1542913832

**Comment by suntong** [comment] 2023-05-11 03:37
it's alright,
