### ISSUE TITLE
The YoutubeEmbed Plugin

### ISSUE THREAD

**Issue by 097115** [suntong/html2md#7] opened 2023-02-14 16:50 UTC
E.g., let's say we have an embedded YouTube iframe. Then this command

    echo '<p>Lorem Ipsum:</p><p style="text-align: center;"><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/PifPVQOFyZI" title="YouTube video player" width="560"></iframe></p>' | html2md -i

...will return just:

    Lorem Ipsum:

Ma be it could catch the iframe's `src` and return it instead of iframe? Like:

    Lorem Ipsum:
    https://www.youtube.com/embed/PifPVQOFyZI

**Comment by suntong** [comment] 2023-05-01 21:52
> ...will return just:
> 
> ```
> Lorem Ipsum:
> ```

Hmm... this is what `html2md` supposed to be doing -- getting the html text, not html attributes. So I'll close it instead, for being out of the scope of this tool.

**Comment by suntong** [comment] 2023-05-01 21:59
That being said, I'll try to add the feature to  
https://github.com/suntong/cascadia  
as it is not supported there as of now...

**Comment by suntong** [comment] 2023-05-01 22:09
> That being said, I'll try to add the feature to https://github.com/suntong/cascadia as it is not supported there as of now...

Ahh, turned out that it is supported now. See https://github.com/suntong/cascadia/wiki#attribute-selection

```
echo '<p>Lorem Ipsum:</p><p style="text-align: center;"><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/PifPVQOFyZI" title="YouTube video player" width="560"></iframe></p>' | cascadia -o -i -c 'p' -p 'src=attr[src]:iframe'
src

https://www.youtube.com/embed/PifPVQOFyZI

```

**Comment by 097115** [comment] 2023-05-02 02:39
@suntong, thank you for your comments!

However, my point was to extract BOTH the text AND the YouTube's iframe's source :) (To make some random web page actually readable in the terminal).

With `cascadia`, however, I can't seem to find a way to keep BOTH the common `<p>` entries and the iframe's src: the example you showed above just skips the common text (`Lorem ipsum` in this example), and if I try something like 

    echo '<p>Lorem Ipsum:</p>
          <p style="text-align: center;"><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/PifPVQOFyZI" title="YouTube video player" width="560"></iframe></p>' \
    | cascadia -o -i -c 'p' -c 'src=attr[src]:iframe'

when it doesn't strips HTML :)

But may be there's some workaround? To keep both the text and the iframe's source?

Thanks again :)

**Comment by 097115** [comment] 2023-05-02 05:26
@suntong 

> for being out of the scope of this tool.

On a second thought, please, consider this example:

    echo '<p>Lorem Ipsum:</p>
          <p><img src="https://some.picture/url.jpg"></p>' | html2md -i

which will produce the following output:

    Lorem Ipsum:

    ![](https://some.picture/url.jpg)

So, if `html2md` considers HTML attributes for `img`, then why shouldn't it consider those in other cases? :)

Those `src` are a part of the content, they logically and consistently connect the currently processed page with the other resources, so stripping those simply breaks the narrative, no? 

What do you think?

**Comment by suntong** [comment] 2023-05-02 14:11
> However, my point was to extract BOTH the text AND the YouTube's iframe's source

In that case, maybe take a look at the 
`--plugin-youtube`, the Plugin of YoutubeEmbed from the html2md lib.

**Comment by 097115** [comment] 2023-05-03 02:59
> In that case, maybe take a look at the `--plugin-youtube`

May be I'm doing something wrong but I added it to the [sample command](https://github.com/suntong/html2md/issues/7#issue-1584502329), and it changes nothing for me?

**Comment by suntong** [comment] 2023-05-03 03:12
> it changes nothing for me?

Ah, yeah, me neither, and I tried the input from 
https://github.com/JohannesKaufmann/html-to-markdown/blob/8eb812b8869e447bb712afdb05d8627da816ecae/testdata/TestRealWorld/golang.org/input.html#L162-L167
and it doesn't work either. 

And it turns out to be caused by https://github.com/suntong/html2md/issues/1: 

> All Plugins that are still named with EXPERIMENTAL_ in upstream are commented out at the moment.

I don't have time to look into it further now.  
Maybe in a month or two...

**Comment by 097115** [comment] 2023-05-03 03:23
> I don't have time to look into it further now. Maybe in a month or two...

No problem, it's nothing urgent. Thank you for your interest anyway :)

**Comment by suntong** [comment] 2023-05-03 14:48
Hmm, please

- report the issue [upstream](https://github.com/JohannesKaufmann/html-to-markdown/issues), and
- discuss in details with him what you want out of the Plugin of YoutubeEmbed
- if AOK, ask him to remove the `EXPERIMENTAL`. If you have no way to debug the YoutubeEmbed Plugin yourself, you may want to ask him to remove the `EXPERIMENTAL` first, and tell me.

thanks

**Comment by 097115** [comment] 2023-05-04 02:32
> the YoutubeEmbed Plugin

The funny thing is, it's not even a function. I mean, I'm not a programmer at all, so I'm probably missing the elephant in the room, but any other plugin you do map in [prop_html2md.go](https://github.com/suntong/html2md/blob/master/prop_html2md.go), and what do you do with [this](https://github.com/JohannesKaufmann/html-to-markdown/blob/8eb812b8869e447bb712afdb05d8627da816ecae/plugin/youtube.go#L16)?

**Comment by suntong** [comment] 2023-05-04 02:58
> and what do you do with [this](https://github.com/JohannesKaufmann/html-to-markdown/blob/8eb812b8869e447bb712afdb05d8627da816ecae/plugin/youtube.go#L16)?

That's what I meant by _"ask him to remove the EXPERIMENTAL"_. IE, change the `var EXPERIMENTALYoutubeEmbed` to `var YoutubeEmbed`.

Just tell him that you're not a programmer at all, and you have no way to debug the YoutubeEmbed Plugin yourself other than through html2md. Hope that he'd agree with it. But honestly, if you don't know the

`go install github.com/suntong/html2md@latest`

command to build html2md yourself, you might find it very difficult to discuss in details with him what you want out of the Plugin, and have to accept whatever the plugin is doing as-is.

**Comment by suntong** [comment] 2023-05-04 03:03
> The funny thing is, it's not even a function.

Ahh, I know what you meant now. Yes, I agree with you, I have no idea how to use it unless it is a function. OK. let me talk to him instead.

**Comment by 097115** [comment] 2023-12-29 09:11
So, coming back to this issue, I see that *it seems* this was fixed upstream, and you have also released a new version :)

However, the example mentioned above:

    echo '<p>Lorem Ipsum:</p><p style="text-align: center;"><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/PifPVQOFyZI" title="YouTube video player" width="560"></iframe></p>' | html2md -i --plugin-youtube

still doesn't work for me. Is it the same for you (or have you managed to extract YouTube links from any actual page), or am I missing something?

Thank you :)

**Comment by suntong** [comment] 2023-12-29 20:00
Per https://github.com/JohannesKaufmann/html-to-markdown/issues/65, there is a new way of doing it -- using iframe plugins, but I haven't got around checking it yet. Have you made any progress using the new version?

**Comment by 097115** [comment] 2023-12-30 04:55
Well, from a user's perspective, nothing has changed, hasn't it?

In order to call the `YoutubeEmbed()` function from [`plugin/iframe_youtube.go`](https://github.com/JohannesKaufmann/html-to-markdown/blob/master/plugin/iframe_youtube.go) I still have to add `--plugin-youtube` argument to my `htmll2md` call, right?

**Comment by suntong** [comment] 2023-12-30 15:03
Well, if it works it works, if it doesn't then doesn't, as _"nothing has changed"_ in this project _yet_.

The key is try to make it work _when it doesn't_, however I don't have time to look into it (and your other issue #19) now and even in near future, about 3 to 5 month, as I'm suppose to be on holiday and relax since 22th, but the reality was that I had been working days _**and nights**_, over 12am midnight each day. 

I encourage you to reach out to upstream and try to figure out how it suppose to work meanwhile.

**Comment by 097115** [comment] 2023-12-30 17:49
So, indeed try to relax, and sorry for bothering you :)

Have a good time, we'll come back to this :)

**Comment by 097115** [comment] 2024-02-09 05:55
@suntong, I hope you are doing well!

Speaking of YouTube support, it looks that when releasing the last version, you simply forgot to enable it here: https://github.com/suntong/html2md/blob/ec1b5c2d11c93a5f478a27055b02620a5fb29c33/prop_html2md.go#L131

(Same goes for `PluginVimeoEmbed` but differently from `PluginYouTubeEmbed`, the former takes a [parameter](https://github.com/JohannesKaufmann/html-to-markdown/blob/2ec22598620f8ef6670d70cb6bd5088be3a62ca0/plugin/iframe_vimeo.go#L59), which wasn't exactly obvious to me, and since the last time I saw an embedded Vimeo video was years and years ago, I didn't really bothered :) 

So, TL;DR: after un-commenting the aforesaid lines, it seems to work:

    echo '<p>Lorem Ipsum:</p><p style="text-align: center;"><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/PifPVQOFyZI" title="YouTube video player" width="560"></iframe></p>' | ./h2m -i --plugin-youtube
    Lorem Ipsum:
    
    [![YouTube video player](https://img.youtube.com/vi/PifPVQOFyZI/0.jpg)](https://www.youtube.com/watch?v=PifPVQOFyZI)

I will leave the issue open for now but feel free to close it, since the problem indeed was solved upstream.

**Comment by suntong** [comment] 2024-02-10 21:48
> after un-commenting the aforesaid lines, it seems to work

https://github.com/suntong/html2md/blob/423fe1c8e82eeae227c325036539bd0eabc30a58/prop_html2md.go#L128-L133

So I've just un-commented the aforesaid lines, but it's not enough for me, I'm getting

`undefined: plugin.VimeoEmbed` and `undefined: plugin.YoutubeEmbed`

How did you make it work please?

**Comment by 097115** [comment] 2024-02-11 03:18
Donno, something on your side, I'd say :)

I simply clone this repo, disable Vimeo (since, as I say, [it throws an error](https://github.com/suntong/html2md/actions/runs/7857583150/job/21441636314)), then run 

  - `go mod init html2md_main.go`
  - `go mod tidy`
  - `go build -o html2md`

And that's it.

**Comment by suntong** [comment] 2024-02-13 16:37
Hmm... it won't be as simple as that, as the error was:

not enough arguments in call to plugin.VimeoEmbed
have ()
want (plugin.vimeoVariation)

I.e., some changes have to be made to the code apart from merely enabling
the commented code.

I don't have time to look into it now, maybe in a month or so.

**Comment by suntong** [comment] 2024-02-13 16:38
Oh, "disable Vimeo", ok, will try ...

**Comment by suntong** [comment] 2024-05-24 20:36
html-to-markdown Release v1.6.0 is out, with update to YoutubeEmbed plugin.

I'll find some time to work on this, to catch up with upstream...

**Comment by suntong** [comment] 2024-05-25 13:37
> Oh, "disable Vimeo", ok, will try ...

Duh! It's fixed already!! https://github.com/suntong/html2md/releases/tag/v1.5.0

**Closed by suntong** 2024-05-25 13:37 UTC
Labels: upstream

**Comment by 097115** [comment] 2024-05-25 13:47
@suntong, great work! Thanks :)
